// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "codec.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `chonkle:codec/transform@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_chonkle:codec/transform@0.1.0#encode")))
void __wasm_export_exports_chonkle_codec_transform_encode_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len0 = *((size_t*) (arg0 + (2*sizeof(void*))));
      if (len0 > 0) {
        uint8_t *ptr1 = *((uint8_t **) (arg0 + sizeof(void*)));
        for (size_t i2 = 0; i2 < len0; i2++) {
          uint8_t *base = ptr1 + i2 * (4*sizeof(void*));
          (void) base;
          if ((*((size_t*) (base + sizeof(void*)))) > 0) {
            free(*((uint8_t **) (base + 0)));
          }
          size_t len = *((size_t*) (base + (3*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (base + (2*sizeof(void*))));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
        }
        free(ptr1);
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_chonkle:codec/transform@0.1.0#decode")))
void __wasm_export_exports_chonkle_codec_transform_decode_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len0 = *((size_t*) (arg0 + (2*sizeof(void*))));
      if (len0 > 0) {
        uint8_t *ptr1 = *((uint8_t **) (arg0 + sizeof(void*)));
        for (size_t i2 = 0; i2 < len0; i2++) {
          uint8_t *base = ptr1 + i2 * (4*sizeof(void*));
          (void) base;
          if ((*((size_t*) (base + sizeof(void*)))) > 0) {
            free(*((uint8_t **) (base + 0)));
          }
          size_t len = *((size_t*) (base + (3*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (base + (2*sizeof(void*))));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
        }
        free(ptr1);
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void exports_chonkle_codec_transform_port_name_free(exports_chonkle_codec_transform_port_name_t *ptr) {
  codec_string_free(ptr);
}

void codec_list_u8_free(codec_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void codec_tuple2_port_name_list_u8_free(codec_tuple2_port_name_list_u8_t *ptr) {
  exports_chonkle_codec_transform_port_name_free(&ptr->f0);
  codec_list_u8_free(&ptr->f1);
}

void exports_chonkle_codec_transform_port_map_free(exports_chonkle_codec_transform_port_map_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    codec_tuple2_port_name_list_u8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      codec_tuple2_port_name_list_u8_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_chonkle_codec_transform_result_port_map_string_free(exports_chonkle_codec_transform_result_port_map_string_t *ptr) {
  if (!ptr->is_err) {
    exports_chonkle_codec_transform_port_map_free(&ptr->val.ok);
  } else {
    codec_string_free(&ptr->val.err);
  }
}

void codec_string_set(codec_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void codec_string_dup(codec_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void codec_string_dup_n(codec_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void codec_string_free(codec_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("chonkle:codec/transform@0.1.0#encode")))
uint8_t * __wasm_export_exports_chonkle_codec_transform_encode(uint8_t * arg, size_t arg0) {
  exports_chonkle_codec_transform_port_map_t arg1 = (exports_chonkle_codec_transform_port_map_t) { (codec_tuple2_port_name_list_u8_t*)(arg), (arg0) };
  exports_chonkle_codec_transform_result_port_map_string_t ret;
  exports_chonkle_codec_transform_port_map_t ok;
  codec_string_t err;
  ret.is_err = !exports_chonkle_codec_transform_encode(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const codec_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload2).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload2).ptr;
  } else {
    const exports_chonkle_codec_transform_port_map_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("chonkle:codec/transform@0.1.0#decode")))
uint8_t * __wasm_export_exports_chonkle_codec_transform_decode(uint8_t * arg, size_t arg0) {
  exports_chonkle_codec_transform_port_map_t arg1 = (exports_chonkle_codec_transform_port_map_t) { (codec_tuple2_port_name_list_u8_t*)(arg), (arg0) };
  exports_chonkle_codec_transform_result_port_map_string_t ret;
  exports_chonkle_codec_transform_port_map_t ok;
  codec_string_t err;
  ret.is_err = !exports_chonkle_codec_transform_decode(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const codec_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload2).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload2).ptr;
  } else {
    const exports_chonkle_codec_transform_port_map_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_codec(void);
__attribute__((used))
void __component_type_object_force_link_codec_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_codec();
}
