// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_CODEC_H
#define __BINDINGS_CODEC_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct codec_string_t {
  uint8_t*ptr;
  size_t len;
} codec_string_t;

// A named byte buffer — one port in the port map.
typedef codec_string_t exports_chonkle_codec_transform_port_name_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} codec_list_u8_t;

typedef struct {
  exports_chonkle_codec_transform_port_name_t f0;
  codec_list_u8_t f1;
} codec_tuple2_port_name_list_u8_t;

typedef struct exports_chonkle_codec_transform_port_map_t {
  codec_tuple2_port_name_list_u8_t   *ptr;
  size_t len;
} exports_chonkle_codec_transform_port_map_t;

typedef struct {
  bool is_err;
  union {
    exports_chonkle_codec_transform_port_map_t ok;
    codec_string_t err;
  } val;
} exports_chonkle_codec_transform_result_port_map_string_t;

// Exported Functions from `chonkle:codec/transform@0.1.0`
bool exports_chonkle_codec_transform_encode(exports_chonkle_codec_transform_port_map_t *inputs, exports_chonkle_codec_transform_port_map_t *ret, codec_string_t *err);
bool exports_chonkle_codec_transform_decode(exports_chonkle_codec_transform_port_map_t *inputs, exports_chonkle_codec_transform_port_map_t *ret, codec_string_t *err);

// Helper Functions

void exports_chonkle_codec_transform_port_name_free(exports_chonkle_codec_transform_port_name_t *ptr);

void codec_list_u8_free(codec_list_u8_t *ptr);

void codec_tuple2_port_name_list_u8_free(codec_tuple2_port_name_list_u8_t *ptr);

void exports_chonkle_codec_transform_port_map_free(exports_chonkle_codec_transform_port_map_t *ptr);

void exports_chonkle_codec_transform_result_port_map_string_free(exports_chonkle_codec_transform_result_port_map_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void codec_string_set(codec_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void codec_string_dup(codec_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void codec_string_dup_n(codec_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void codec_string_free(codec_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
